apiVersion: v1
kind: Service
metadata:
  name: message-board-service
spec:
  type: NodePort
  selector:
    app: message-board
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30001   # NodePort range is 30000-32767
